M48
; DRILL file {KiCad 7.0.1-0} date 2023 August 06, Sunday 23:46:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-06T23:46:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X166.891Y-46.492
X171.741Y-46.492
T2
X166.591Y-43.462
X172.041Y-43.462
T0
M30
